"""language: isocode

Revision ID: 14e7799c9ceb
Revises: d74c04a5959f
Create Date: 2020-02-08 10:40:28.635659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e7799c9ceb'
down_revision = 'd74c04a5959f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('languages', 'concordance_html')
    op.drop_column('languages', 'concordnace_md')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('concordnace_md', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('languages', sa.Column('concordance_html', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
