"""initial migration

Revision ID: d74c04a5959f
Revises: 
Create Date: 2020-02-08 10:37:43.245378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74c04a5959f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('languages_isocode_key', 'languages', type_='unique')
    op.drop_column('languages', 'isocode')
    op.drop_column('languages', 'concordnace_md')
    op.drop_column('languages', 'concordance_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('concordance_html', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('languages', sa.Column('concordnace_md', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('languages', sa.Column('isocode', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.create_unique_constraint('languages_isocode_key', 'languages', ['isocode'])
    # ### end Alembic commands ###
