"""remove unique constraint on orthography

Revision ID: f4e0a05994c2
Revises: 35a11e4bd66b
Create Date: 2020-02-19 21:42:36.031527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e0a05994c2'
down_revision = '35a11e4bd66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_terms_orthography', table_name='terms')
    op.create_index(op.f('ix_terms_orthography'), 'terms', ['orthography'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terms_orthography'), table_name='terms')
    op.create_index('ix_terms_orthography', 'terms', ['orthography'], unique=True)
    # ### end Alembic commands ###
